module.exports = {
    'ALGN':'Align Technology',
    'ANET':'Arista Networks',
    'APPN':'Appian',
    'CMG':'Chipotle',
    'CRM':'Salesforce',
    'CRSP':'Crispr',
    'CRWD':'Crowdstrike',
    'FVRR':'Fiverr',
    'IRBT':'iRobot',
    'ISRG':'Intuitive Surgical',
    'JD':'JD.com',
    'KNSL':'Kinsale',
    'LMND':'Lemonade',
    'LOPE':'Grand Canyon Education',
    'MA':'Mastercard',
    'META':'Meta',
    'MKL':'Markel',
    'NFLX':'Netflix',
    'NTB':'Butterfield',
    'NVTA':'Invitae',
    'OKTA':'Okta',
    'PAYC':'Paycom',
    'PJT':'PJT',
    'SFIX':'Stitchfix',
    'SHOP':'Shopify',
    'SIVB':'SVB Financial',
    'SIX':'Six Flags',
    'SQ':'Block',
    'TCX':'Tucows',
    'TEAM':'Atlassian',
    'TSLA':'Tesla',
    'TTD':'Trade Desk',
    'TWLO':'Twilio',
    'UPST':'UPST',
    'WD':'Walker Dunlop',
    'WIX':'Wix',
    'Z':'Zillow',
    'ZG':'Zillow',
    'ZS':'ZScaler',
    'NOW':'ServiceNow',
    'SNOW':'Snowflake',
  }
  
